version: "3.7"

services:
  ansible:
    image: tomfordweb/ansible-control
    container_name: ansible
    entrypoint: ["ansible-playbook", "--vault-password-file", ".vault_password"]
    volumes:
      - ./:/ansible
      - /home/$USER/.ssh/id_rsa.pub:/ansible/.public_ssh_key:ro
      - /home/$USER/.vault_password:/ansible/.vault_password:ro
      - $SSH_AUTH_SOCK:/ssh-agent
    extra_hosts:
      - homelab:${HOMELAB_IP?Required Value}
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      PVE_ADMIN_USER_PASSWORD: ${PVE_ADMIN_USER_PASSWORD?Required Value}
      PVE_CONTAINER_PASSWORD: ${PVE_CONTAINER_PASSWORD?Required Value}
      PVE_ROOT_PASSWORD: ${PVE_ROOT_PASSWORD?Required Value}
