---
# tasks file for roles/docker-base

- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: "yes"

- name: Install docker dependancies
  apt:
    state: present
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  tags: ["packages"]

- name: Add docker official GPG key
  become_user: root
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: ["packages"]

- name: Add the docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_facts.distribution_release }} stable
  tags: ["packages"]

- name: Update apt cache and install docker
  apt:
    update_cache: yes
    state: present
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tags: ["packages"]
