---
# tasks file for roles/pve-users
- name: "Create the 'pve_admins' groups"
  tags: ["auth"]
  with_items: "{{ pve_admins }}"
  proxmox_group:
    name: "{{ item.group }}"

- name: "Create the 'pve_admins' users"
  tags: ["auth"]
  with_items: "{{ pve_admins }}"
  proxmox_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    groups:
      - "{{ item.group }}"

- name: "Create the 'pve_admins' roles"
  tags: ["auth"]
  with_items: "{{ pve_admins }}"
  proxmox_acl:
    path: "{{ item.acl.path }}"
    roles: "{{ item.acl.roles }}"
    users:
      - "{{ item.name }}"
