---
- name: Install 'communtiy.docker' apt dependencies
  apt:
    pkg:
      - python3
      - python3-pip

- name: Install 'community.docker' pip dependencies
  pip:
    name:
      - docker

- name: Init a new swarm with default parameters
  when: inventory_hostname in groups['swarmmanagers']
  community.docker.docker_swarm:
    state: present
  register: swarm_info

- name: Register the join token
  when: inventory_hostname in groups['swarmmanagers']
  set_fact:
    swarm_join_token: "{{ swarm_info.swarm_facts.JoinTokens.Manager }}"

# TODO: How to loop this so the hostname isnt hardcoded
- debug:
    msg: "{{ hostvars['swarm-manager-01']['swarm_join_token'] }}"

- name: Add nodes
  when: inventory_hostname in groups['swarmnodes']
  community.docker.docker_swarm:
    state: join
    # advertise_addr: 192.168.1.2
    join_token: "{{ hostvars['swarm-manager-01']['swarm_join_token'] }}"
    remote_addrs:
      ["{{ hostvars['swarm-manager-01']['ansible_default_ipv4']['address'] }}"]
