---
- name: Install 'communtiy.docker' apt dependencies
  apt:
    pkg:
      - python3
      - python3-pip

- name: Install 'community.docker' pip dependencies
  pip:
    name:
      - docker

- name: Init a new swarm with default parameters
  when: inventory_hostname in groups['swarmmanagers']
  community.docker.docker_swarm:
    state: present
  register: swarm_info

# For every swarm manager, register a swarm_join_token fact
- name: Register the join token
  when: inventory_hostname in groups['swarmmanagers']
  set_fact:
    swarm_join_token: "{{ swarm_info.swarm_facts.JoinTokens.Manager }}"

# For every docker node, look at the swarm manager variable for each host
# And access the fact we set above
- name: Add nodes
  when: inventory_hostname in groups['swarmnodes']
  community.docker.docker_swarm:
    state: join
    join_token: "{{ hostvars[ hostvars[inventory_hostname]['manager']]['swarm_join_token'] }}"
    remote_addrs:
      [
        "{{ hostvars[ hostvars[inventory_hostname]['manager']]['ansible_default_ipv4']['address'] }}",
      ]
