---
# This is the configuration for the main pve admin user
node_name: pve

#######################
# Node administrators #
#######################
# A list of all of the admins on every host in this inventory
pve_admins:
  - name: midas@pve
    password: "{{ lookup('env', 'PVE_ADMIN_USER_PASSWORD') }}"

    acl:
      path: "/"
      roles: ["PVETemplateUser", "PVEVMAdmin", "PVEDatastoreAdmin"]
    group: admin
# The administrator that we will be running tasks as
default_admin: "{{ pve_admins[0] }}"
# Necessary when creating containers where modifing features

# Shared password for lxc containers:w

vm_storage_name: pve-vms

####################
# Host Definitions #
####################
pve_hosts:
  # Docker Swarm
  # Since these run in LXC containers, they must be created as root
  # This is because only root@pam can adjust the features of a container.
  # In order to run containers in containers, you must allow nesting and keyctl
  - hostname: swarm-manager-01
    vmid: "301"

  - hostname: swarm-node-01-01
    vmid: "302"

  - hostname: swarm-node-01-02
    vmid: "303"

  - hostname: swarm-node-01-03
    vmid: "304"

  - hostname: swarm-node-01-04
    vmid: "305"

  - hostname: swarm-node-01-05
    vmid: "307"
